#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}

echo "Creating jibri user and group"
# Create the Jibri user and group
useradd --system --create-home jibri
echo "Done creating jibri user and group"
usermod -a -G jibri,audio,video jibri
echo "jibri user added to aduio, video and jibri groups"

# Move the asoundrc file to the jibri home directory
mv /etc/jitsi/jibri/asoundrc /home/jibri/.asoundrc

mkdir /home/jibri/.icewm
mv /etc/jitsi/jibri/icewm.preferences /home/jibri/.icewm/preferences
